baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Kross | Hugo Portfolio Template"
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[params]
address = "A-7100 Neusiedl"
author = "Hans"
copyright = "(c) skale.io 2021"
description = "This is a forestry hugo site"
email = "hi@skale.io"
google_analitycs_id = ""
home = "Home"
logo = "images/skaleio_green2_mir5tc.png"
phone = "+43 660 7383285"
theme_color = "#41228e"
[params.contact]
enable = true
form_action = "me@skale.io"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://www.linkedin.com/in/johannwaldherr/"
icon = "ti-linkedin"
[[params.social]]
URL = "https://twitter.com/woodmastr"
icon = "ti-twitter-alt"
